name: Auto Update
on:
  schedule:
    - cron:  "0 8 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: bash ./host.sh
      
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.15.0
      with:
           commit_message: Auto Update
           branch: master
           commit_options: '--no-verify --signoff'
           repository: .
           commit_user_name: FusionPlmH
           commit_user_email: leemenhin@gmail.com
           push_options: '--force'
